export const PHRASES = [
  "please!!! 🥺",
  "pretty please!!!",
  "come on!!!",
  "are you sure?!",
  "just this once!!! 🥹",
  "hear me out!!!",
  "give me chance!!!",
  "one more try?!",
  "dont say no!!! 😭",
  "be nice please!!!",
  "im begging you!!! 🙏",
  "please say yes!!!",
  "please consider it?!",
  "have a heart!!! ❤️",
  "do me favor!!!",
  "i need this!!!",
  "please dont!!!",
  "say yes please!!! 🙏",
  "please say yes!!!",
  "dont do this!!!",
  "please stop!!!",
  "have mercy!!! 🥺",
  "please rethink?!",
];
