/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YesRouteImport } from './routes/yes'
import { Route as IndexRouteImport } from './routes/index'

const YesRoute = YesRouteImport.update({
  id: '/yes',
  path: '/yes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/yes': typeof YesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/yes': typeof YesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/yes': typeof YesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/yes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/yes'
  id: '__root__' | '/' | '/yes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YesRoute: typeof YesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yes': {
      id: '/yes'
      path: '/yes'
      fullPath: '/yes'
      preLoaderRoute: typeof YesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YesRoute: YesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
